builder refactoring

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -1,5 +1,5 @@
 FROM centos:latest
-################################################################################
+#################################################################################
 # Package Lists
 ARG varListRpms="\
              git \
@@ -26,7 +26,7 @@ ARG varListPip="\
              ansible \
              "
 
-################################################################################
+#################################################################################
 # version tracking
 ARG varVerOpenshift="${varVerOpenshift}"
 ARG varVerTerraform="${varVerTerraform}"
@@ -39,67 +39,67 @@ ARG varUrlOpenshift="https://mirror.openshift.com/pub/openshift-v4/x86_64/client
 ARG varUrlTerraform="https://releases.hashicorp.com/terraform/${varVerTerraform}/terraform_${varVerTerraform}_linux_amd64.zip"
 ARG varUrlJq="https://github.com/stedolan/jq/releases/download/jq-${varVerJq}/jq-linux64"
 
-################################################################################
-RUN set -ex \
-     && mkdir -p ${varDirDependencies}/pip  \
-     && mkdir -p ${varDirDependencies}/rpm  \
-     && mkdir -p ${varDirDependencies}/curl \
+#################################################################################
+RUN set -ex                                                                     \
+     && mkdir -p ${varDirDependencies}/pip                                      \
+     && mkdir -p ${varDirDependencies}/rpm                                      \
+     && mkdir -p ${varDirDependencies}/curl                                     \
     && echo
 
-RUN set -ex \
-     && yum update  -y --setopt=tsflags=nodocs \
-     && yum install -y --setopt=tsflags=nodocs \
-          python3-pip \
+RUN set -ex                                                                     \
+     && yum update  -y --setopt=tsflags=nodocs                                  \
+     && yum install -y --setopt=tsflags=nodocs python3-pip                      \
     && echo
-#         yum-plugin-downloadonly \
 
-# Change base workdir
+# Gather Dependencies | rpm
 WORKDIR /tmp/builder/artifacts/rpm
-
-RUN set -ex \
-     && yum install -y \
-          --downloadonly \
-          --downloaddir=${varDirDependencies}/rpm \
-          ${varListRpms} \
+RUN set -ex                                                                     \
+     && yum install -y                                                          \
+          --downloadonly                                                        \
+          --downloaddir=${varDirDependencies}/rpm                               \
+          ${varListRpms}                                                        \
     && echo
 
-# Change base workdir
+# Gather Dependencies | curl
 WORKDIR ${varDirDependencies}/curl
-
-RUN set -ex \
-     && curl -LO ${varUrlOpenshift} \
-     && curl -LO ${varUrlTerraform} \
-     && curl -LO ${varUrlOsInst}    \
-     && curl -LO ${varUrlJq}        \
+RUN set -ex                                                                     \
+     && curl -LO ${varUrlOpenshift}                                             \
+     && curl -LO ${varUrlTerraform}                                             \
+     && curl -LO ${varUrlOsInst}                                                \
+     && curl -LO ${varUrlJq}                                                    \
     && echo
 
-# Change base workdir
+# Gather Dependencies | Pip
 WORKDIR ${varDirDependencies}/pip
-
-RUN set -ex \
-     && pip3 download \
-            -d ${varDirDependencies}/pip \
-          ${varListPip}                  \
+RUN set -ex                                                                     \
+     && pip3 download                                                           \
+            -d ${varDirDependencies}/pip                                        \
+          ${varListPip}                                                         \
     && echo
 
-# Change base workdir
+# Create Unified Tarball
 WORKDIR /tmp/
-RUN tar -czvf dependencies.tar.gz dependencies
+RUN set -ex                                                                     \
+     && tar -czvf dependencies.tar.gz dependencies                              \
+     && du -sh dependencies.tar.gz                                              \
+    && echo
 
-RUN yum clean all \
-    && rm -rf \
-        /tmp/dependencies \
-        /var/cache/* \
-        /var/log/dnf* \
-        /var/log/yum* \
+# Cleanup container
+RUN yum clean all                                                               \
+    && history -c                                                               \
+    && rm -rf                                                                   \
+        /tmp/dependencies                                                       \
+        /var/cache/*                                                            \
+        /var/log/dnf*                                                           \
+        /var/log/yum*                                                           \
    ; echo
 
-################################################################################
+#################################################################################
 # ContainerOne | Cloud Orchestration Tools - Point of Origin
 ENV versOCP="${varVerOpenshift}"
-LABEL Vendor="containercraft.io"     \
-      OpenShift="${versOCP}"         \
-      BuildDate="${varRunDate}"      \
-      maintainer="ContainerCraft.io" \
+LABEL Vendor="containercraft.io"                                                \
+      OpenShift="${versOCP}"                                                    \
+      BuildDate="${varRunDate}"                                                 \
+      maintainer="ContainerCraft.io"                                            \
       License=GPLv3 
 CMD ["bash"]
